//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.19 at 01:24:49 PM PDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.suretrak21.com/ST_Track", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.spawar.icode.radar;
