//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.19 at 01:24:49 PM PDT 
//


package com.spawar.icode.radar;

import java.math.BigInteger;
import javax.xml.bind.annotation.*;


/**
 * <p>Java class for ST_Track_surf_t complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ST_Track_surf_t">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="msgID" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="portalName" type="{http://www.suretrak21.com/ST_Track}portalName_t"/>
 *         &lt;element name="msgTime" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="hdr" type="{http://www.suretrak21.com/ST_Track}AllTrkHdr_t"/>
 *         &lt;element name="surf" type="{http://www.suretrak21.com/ST_Track}track_surf_t"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ST_Track_surf_t", propOrder = {
    "msgID",
    "portalName",
    "msgTime",
    "hdr",
    "surf"
})
@XmlRootElement(name = "ST_Track_surf")
public class STTrackSurfT {

    @XmlElement(required = true)
    protected BigInteger msgID;
    @XmlElement(required = true)
    protected String portalName;
    protected double msgTime;
    @XmlElement(required = true)
    protected AllTrkHdrT hdr;
    @XmlElement(required = true)
    protected TrackSurfT surf;

    /**
     * Gets the value of the msgID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMsgID() {
        return msgID;
    }

    /**
     * Sets the value of the msgID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMsgID(BigInteger value) {
        this.msgID = value;
    }

    /**
     * Gets the value of the portalName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPortalName() {
        return portalName;
    }

    /**
     * Sets the value of the portalName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPortalName(String value) {
        this.portalName = value;
    }

    /**
     * Gets the value of the msgTime property.
     * 
     */
    public double getMsgTime() {
        return msgTime;
    }

    /**
     * Sets the value of the msgTime property.
     * 
     */
    public void setMsgTime(double value) {
        this.msgTime = value;
    }

    /**
     * Gets the value of the hdr property.
     * 
     * @return
     *     possible object is
     *     {@link AllTrkHdrT }
     *     
     */
    public AllTrkHdrT getHdr() {
        return hdr;
    }

    /**
     * Sets the value of the hdr property.
     * 
     * @param value
     *     allowed object is
     *     {@link AllTrkHdrT }
     *     
     */
    public void setHdr(AllTrkHdrT value) {
        this.hdr = value;
    }

    /**
     * Gets the value of the surf property.
     * 
     * @return
     *     possible object is
     *     {@link TrackSurfT }
     *     
     */
    public TrackSurfT getSurf() {
        return surf;
    }

    /**
     * Sets the value of the surf property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrackSurfT }
     *     
     */
    public void setSurf(TrackSurfT value) {
        this.surf = value;
    }

}
