//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.19 at 01:24:49 PM PDT 
//


package com.spawar.icode.radar;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for track_surf_t complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="track_surf_t">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="vi" type="{http://www.suretrak21.com/ST_Track}vessel_info_t"/>
 *         &lt;element name="reportTime" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="plotSize" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="range" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="acquired" type="{http://www.suretrak21.com/ST_Track}TRK_AcqMode_t"/>
 *         &lt;element name="aisSup" type="{http://www.suretrak21.com/ST_Track}sup_ais_data_t"/>
 *         &lt;element name="returnQuality" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "track_surf_t", propOrder = {
    "vi",
    "reportTime",
    "plotSize",
    "range",
    "acquired",
    "aisSup",
    "returnQuality"
})
public class TrackSurfT {

    @XmlElement(required = true)
    protected VesselInfoT vi;
    protected double reportTime;
    protected float plotSize;
    protected float range;
    @XmlElement(required = true)
    protected BigInteger acquired;
    @XmlElement(required = true)
    protected SupAisDataT aisSup;
    @XmlElement(required = true)
    protected BigInteger returnQuality;

    /**
     * Gets the value of the vi property.
     * 
     * @return
     *     possible object is
     *     {@link VesselInfoT }
     *     
     */
    public VesselInfoT getVi() {
        return vi;
    }

    /**
     * Sets the value of the vi property.
     * 
     * @param value
     *     allowed object is
     *     {@link VesselInfoT }
     *     
     */
    public void setVi(VesselInfoT value) {
        this.vi = value;
    }

    /**
     * Gets the value of the reportTime property.
     * 
     */
    public double getReportTime() {
        return reportTime;
    }

    /**
     * Sets the value of the reportTime property.
     * 
     */
    public void setReportTime(double value) {
        this.reportTime = value;
    }

    /**
     * Gets the value of the plotSize property.
     * 
     */
    public float getPlotSize() {
        return plotSize;
    }

    /**
     * Sets the value of the plotSize property.
     * 
     */
    public void setPlotSize(float value) {
        this.plotSize = value;
    }

    /**
     * Gets the value of the range property.
     * 
     */
    public float getRange() {
        return range;
    }

    /**
     * Sets the value of the range property.
     * 
     */
    public void setRange(float value) {
        this.range = value;
    }

    /**
     * Gets the value of the acquired property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAcquired() {
        return acquired;
    }

    /**
     * Sets the value of the acquired property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAcquired(BigInteger value) {
        this.acquired = value;
    }

    /**
     * Gets the value of the aisSup property.
     * 
     * @return
     *     possible object is
     *     {@link SupAisDataT }
     *     
     */
    public SupAisDataT getAisSup() {
        return aisSup;
    }

    /**
     * Sets the value of the aisSup property.
     * 
     * @param value
     *     allowed object is
     *     {@link SupAisDataT }
     *     
     */
    public void setAisSup(SupAisDataT value) {
        this.aisSup = value;
    }

    /**
     * Gets the value of the returnQuality property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getReturnQuality() {
        return returnQuality;
    }

    /**
     * Sets the value of the returnQuality property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setReturnQuality(BigInteger value) {
        this.returnQuality = value;
    }

}
