//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.19 at 01:24:49 PM PDT 
//


package com.spawar.icode.radar;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.spawar.icode.radar package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CameraIdAvailable_QNAME = new QName("http://www.suretrak21.com/ST_Track", "camera_id_available");
    private final static QName _STTrackAir_QNAME = new QName("http://www.suretrak21.com/ST_Track", "ST_Track_air");
    private final static QName _CameraIdRequest_QNAME = new QName("http://www.suretrak21.com/ST_Track", "camera_id_request");
    private final static QName _STTrackSurf_QNAME = new QName("http://www.suretrak21.com/ST_Track", "ST_Track_surf");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.spawar.icode.radar
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link VectorT3 }
     * 
     */
    public VectorT3 createVectorT3() {
        return new VectorT3();
    }

    /**
     * Create an instance of {@link SdsTrackIDStruct }
     * 
     */
    public SdsTrackIDStruct createSdsTrackIDStruct() {
        return new SdsTrackIDStruct();
    }

    /**
     * Create an instance of {@link STTrackSurfT }
     * 
     */
    public STTrackSurfT createSTTrackSurfT() {
        return new STTrackSurfT();
    }

    /**
     * Create an instance of {@link AllTrkHdrT }
     * 
     */
    public AllTrkHdrT createAllTrkHdrT() {
        return new AllTrkHdrT();
    }

    /**
     * Create an instance of {@link TrackAirT }
     * 
     */
    public TrackAirT createTrackAirT() {
        return new TrackAirT();
    }

    /**
     * Create an instance of {@link TrackSurfT }
     * 
     */
    public TrackSurfT createTrackSurfT() {
        return new TrackSurfT();
    }

    /**
     * Create an instance of {@link STTrackAirT }
     * 
     */
    public STTrackAirT createSTTrackAirT() {
        return new STTrackAirT();
    }

    /**
     * Create an instance of {@link PointT3 }
     * 
     */
    public PointT3 createPointT3() {
        return new PointT3();
    }

    /**
     * Create an instance of {@link SupAisDataT }
     * 
     */
    public SupAisDataT createSupAisDataT() {
        return new SupAisDataT();
    }

    /**
     * Create an instance of {@link VesselInfoT }
     * 
     */
    public VesselInfoT createVesselInfoT() {
        return new VesselInfoT();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.suretrak21.com/ST_Track", name = "camera_id_available")
    public JAXBElement<BigInteger> createCameraIdAvailable(BigInteger value) {
        return new JAXBElement<BigInteger>(_CameraIdAvailable_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link STTrackAirT }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.suretrak21.com/ST_Track", name = "ST_Track_air")
    public JAXBElement<STTrackAirT> createSTTrackAir(STTrackAirT value) {
        return new JAXBElement<STTrackAirT>(_STTrackAir_QNAME, STTrackAirT.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.suretrak21.com/ST_Track", name = "camera_id_request")
    public JAXBElement<Integer> createCameraIdRequest(Integer value) {
        return new JAXBElement<Integer>(_CameraIdRequest_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link STTrackSurfT }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.suretrak21.com/ST_Track", name = "ST_Track_surf")
    public JAXBElement<STTrackSurfT> createSTTrackSurf(STTrackSurfT value) {
        return new JAXBElement<STTrackSurfT>(_STTrackSurf_QNAME, STTrackSurfT.class, null, value);
    }

}
