//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.19 at 01:24:49 PM PDT 
//


package com.spawar.icode.radar;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for sup_ais_data_t complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="sup_ais_data_t">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="userId" type="{http://www.suretrak21.com/ST_Track}userId_t"/>
 *         &lt;element name="navStatus" type="{http://www.suretrak21.com/ST_Track}navStatus_t"/>
 *         &lt;element name="ROT" type="{http://www.suretrak21.com/ST_Track}ROT_t"/>
 *         &lt;element name="bLessThan10MetersError" type="{http://www.suretrak21.com/ST_Track}bLessThan10MetersError_t"/>
 *         &lt;element name="TypeOfPositionDevice" type="{http://www.suretrak21.com/ST_Track}TypeOfPositionDevice_t"/>
 *         &lt;element name="ReportLat" type="{http://www.suretrak21.com/ST_Track}lat_t"/>
 *         &lt;element name="ReportLon" type="{http://www.suretrak21.com/ST_Track}lon_t"/>
 *         &lt;element name="bCenterPositionValid" type="{http://www.suretrak21.com/ST_Track}bCenterPositionValid_t"/>
 *         &lt;element name="CenterLat" type="{http://www.suretrak21.com/ST_Track}lat_t"/>
 *         &lt;element name="CenterLon" type="{http://www.suretrak21.com/ST_Track}lon_t"/>
 *         &lt;element name="corner1Lat" type="{http://www.suretrak21.com/ST_Track}lat_t"/>
 *         &lt;element name="corner1Lon" type="{http://www.suretrak21.com/ST_Track}lon_t"/>
 *         &lt;element name="corner2Lat" type="{http://www.suretrak21.com/ST_Track}lat_t"/>
 *         &lt;element name="corner2Lon" type="{http://www.suretrak21.com/ST_Track}lon_t"/>
 *         &lt;element name="corner3Lat" type="{http://www.suretrak21.com/ST_Track}lat_t"/>
 *         &lt;element name="corner3Lon" type="{http://www.suretrak21.com/ST_Track}lon_t"/>
 *         &lt;element name="corner4Lat" type="{http://www.suretrak21.com/ST_Track}lat_t"/>
 *         &lt;element name="corner4Lon" type="{http://www.suretrak21.com/ST_Track}lon_t"/>
 *         &lt;element name="typeOfShip1" type="{http://www.suretrak21.com/ST_Track}typeOfShip1_t"/>
 *         &lt;element name="typeOfShip2" type="{http://www.suretrak21.com/ST_Track}typeOfShip2_t"/>
 *         &lt;element name="trueHeading" type="{http://www.suretrak21.com/ST_Track}heading_t"/>
 *         &lt;element name="callSign" type="{http://www.suretrak21.com/ST_Track}callSign_t"/>
 *         &lt;element name="name" type="{http://www.suretrak21.com/ST_Track}name21_t"/>
 *         &lt;element name="dimensionLength" type="{http://www.suretrak21.com/ST_Track}dimensionLength_t"/>
 *         &lt;element name="dimensionWidth" type="{http://www.suretrak21.com/ST_Track}dimensionWidth_t"/>
 *         &lt;element name="ETAmonth" type="{http://www.suretrak21.com/ST_Track}month_t"/>
 *         &lt;element name="ETAday" type="{http://www.suretrak21.com/ST_Track}day_t"/>
 *         &lt;element name="ETAhour" type="{http://www.suretrak21.com/ST_Track}hour_t"/>
 *         &lt;element name="ETAminute" type="{http://www.suretrak21.com/ST_Track}minute_t"/>
 *         &lt;element name="maxDraught" type="{http://www.suretrak21.com/ST_Track}maxDraught_t"/>
 *         &lt;element name="destination" type="{http://www.suretrak21.com/ST_Track}destination_t"/>
 *         &lt;element name="altitudeGNSS" type="{http://www.suretrak21.com/ST_Track}altitude_t"/>
 *         &lt;element name="bSurfaceTrack" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="bMobileTrack" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="bSensorSite" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="bClassA" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sup_ais_data_t", propOrder = {
    "userId",
    "navStatus",
    "rot",
    "bLessThan10MetersError",
    "typeOfPositionDevice",
    "reportLat",
    "reportLon",
    "bCenterPositionValid",
    "centerLat",
    "centerLon",
    "corner1Lat",
    "corner1Lon",
    "corner2Lat",
    "corner2Lon",
    "corner3Lat",
    "corner3Lon",
    "corner4Lat",
    "corner4Lon",
    "typeOfShip1",
    "typeOfShip2",
    "trueHeading",
    "callSign",
    "name",
    "dimensionLength",
    "dimensionWidth",
    "etAmonth",
    "etAday",
    "etAhour",
    "etAminute",
    "maxDraught",
    "destination",
    "altitudeGNSS",
    "bSurfaceTrack",
    "bMobileTrack",
    "bSensorSite",
    "bClassA"
})
public class SupAisDataT {

    protected int userId;
    protected int navStatus;
    @XmlElement(name = "ROT")
    protected double rot;
    protected int bLessThan10MetersError;
    @XmlElement(name = "TypeOfPositionDevice")
    protected int typeOfPositionDevice;
    @XmlElement(name = "ReportLat")
    protected double reportLat;
    @XmlElement(name = "ReportLon")
    protected double reportLon;
    protected int bCenterPositionValid;
    @XmlElement(name = "CenterLat")
    protected double centerLat;
    @XmlElement(name = "CenterLon")
    protected double centerLon;
    protected double corner1Lat;
    protected double corner1Lon;
    protected double corner2Lat;
    protected double corner2Lon;
    protected double corner3Lat;
    protected double corner3Lon;
    protected double corner4Lat;
    protected double corner4Lon;
    protected int typeOfShip1;
    protected int typeOfShip2;
    protected double trueHeading;
    @XmlElement(required = true)
    protected String callSign;
    @XmlElement(required = true)
    protected String name;
    protected int dimensionLength;
    protected int dimensionWidth;
    @XmlElement(name = "ETAmonth")
    protected int etAmonth;
    @XmlElement(name = "ETAday")
    protected int etAday;
    @XmlElement(name = "ETAhour")
    protected int etAhour;
    @XmlElement(name = "ETAminute")
    protected int etAminute;
    protected int maxDraught;
    @XmlElement(required = true)
    protected String destination;
    protected int altitudeGNSS;
    protected boolean bSurfaceTrack;
    protected boolean bMobileTrack;
    protected boolean bSensorSite;
    protected boolean bClassA;

    /**
     * Gets the value of the userId property.
     * 
     */
    public int getUserId() {
        return userId;
    }

    /**
     * Sets the value of the userId property.
     * 
     */
    public void setUserId(int value) {
        this.userId = value;
    }

    /**
     * Gets the value of the navStatus property.
     * 
     */
    public int getNavStatus() {
        return navStatus;
    }

    /**
     * Sets the value of the navStatus property.
     * 
     */
    public void setNavStatus(int value) {
        this.navStatus = value;
    }

    /**
     * Gets the value of the rot property.
     * 
     */
    public double getROT() {
        return rot;
    }

    /**
     * Sets the value of the rot property.
     * 
     */
    public void setROT(double value) {
        this.rot = value;
    }

    /**
     * Gets the value of the bLessThan10MetersError property.
     * 
     */
    public int getBLessThan10MetersError() {
        return bLessThan10MetersError;
    }

    /**
     * Sets the value of the bLessThan10MetersError property.
     * 
     */
    public void setBLessThan10MetersError(int value) {
        this.bLessThan10MetersError = value;
    }

    /**
     * Gets the value of the typeOfPositionDevice property.
     * 
     */
    public int getTypeOfPositionDevice() {
        return typeOfPositionDevice;
    }

    /**
     * Sets the value of the typeOfPositionDevice property.
     * 
     */
    public void setTypeOfPositionDevice(int value) {
        this.typeOfPositionDevice = value;
    }

    /**
     * Gets the value of the reportLat property.
     * 
     */
    public double getReportLat() {
        return reportLat;
    }

    /**
     * Sets the value of the reportLat property.
     * 
     */
    public void setReportLat(double value) {
        this.reportLat = value;
    }

    /**
     * Gets the value of the reportLon property.
     * 
     */
    public double getReportLon() {
        return reportLon;
    }

    /**
     * Sets the value of the reportLon property.
     * 
     */
    public void setReportLon(double value) {
        this.reportLon = value;
    }

    /**
     * Gets the value of the bCenterPositionValid property.
     * 
     */
    public int getBCenterPositionValid() {
        return bCenterPositionValid;
    }

    /**
     * Sets the value of the bCenterPositionValid property.
     * 
     */
    public void setBCenterPositionValid(int value) {
        this.bCenterPositionValid = value;
    }

    /**
     * Gets the value of the centerLat property.
     * 
     */
    public double getCenterLat() {
        return centerLat;
    }

    /**
     * Sets the value of the centerLat property.
     * 
     */
    public void setCenterLat(double value) {
        this.centerLat = value;
    }

    /**
     * Gets the value of the centerLon property.
     * 
     */
    public double getCenterLon() {
        return centerLon;
    }

    /**
     * Sets the value of the centerLon property.
     * 
     */
    public void setCenterLon(double value) {
        this.centerLon = value;
    }

    /**
     * Gets the value of the corner1Lat property.
     * 
     */
    public double getCorner1Lat() {
        return corner1Lat;
    }

    /**
     * Sets the value of the corner1Lat property.
     * 
     */
    public void setCorner1Lat(double value) {
        this.corner1Lat = value;
    }

    /**
     * Gets the value of the corner1Lon property.
     * 
     */
    public double getCorner1Lon() {
        return corner1Lon;
    }

    /**
     * Sets the value of the corner1Lon property.
     * 
     */
    public void setCorner1Lon(double value) {
        this.corner1Lon = value;
    }

    /**
     * Gets the value of the corner2Lat property.
     * 
     */
    public double getCorner2Lat() {
        return corner2Lat;
    }

    /**
     * Sets the value of the corner2Lat property.
     * 
     */
    public void setCorner2Lat(double value) {
        this.corner2Lat = value;
    }

    /**
     * Gets the value of the corner2Lon property.
     * 
     */
    public double getCorner2Lon() {
        return corner2Lon;
    }

    /**
     * Sets the value of the corner2Lon property.
     * 
     */
    public void setCorner2Lon(double value) {
        this.corner2Lon = value;
    }

    /**
     * Gets the value of the corner3Lat property.
     * 
     */
    public double getCorner3Lat() {
        return corner3Lat;
    }

    /**
     * Sets the value of the corner3Lat property.
     * 
     */
    public void setCorner3Lat(double value) {
        this.corner3Lat = value;
    }

    /**
     * Gets the value of the corner3Lon property.
     * 
     */
    public double getCorner3Lon() {
        return corner3Lon;
    }

    /**
     * Sets the value of the corner3Lon property.
     * 
     */
    public void setCorner3Lon(double value) {
        this.corner3Lon = value;
    }

    /**
     * Gets the value of the corner4Lat property.
     * 
     */
    public double getCorner4Lat() {
        return corner4Lat;
    }

    /**
     * Sets the value of the corner4Lat property.
     * 
     */
    public void setCorner4Lat(double value) {
        this.corner4Lat = value;
    }

    /**
     * Gets the value of the corner4Lon property.
     * 
     */
    public double getCorner4Lon() {
        return corner4Lon;
    }

    /**
     * Sets the value of the corner4Lon property.
     * 
     */
    public void setCorner4Lon(double value) {
        this.corner4Lon = value;
    }

    /**
     * Gets the value of the typeOfShip1 property.
     * 
     */
    public int getTypeOfShip1() {
        return typeOfShip1;
    }

    /**
     * Sets the value of the typeOfShip1 property.
     * 
     */
    public void setTypeOfShip1(int value) {
        this.typeOfShip1 = value;
    }

    /**
     * Gets the value of the typeOfShip2 property.
     * 
     */
    public int getTypeOfShip2() {
        return typeOfShip2;
    }

    /**
     * Sets the value of the typeOfShip2 property.
     * 
     */
    public void setTypeOfShip2(int value) {
        this.typeOfShip2 = value;
    }

    /**
     * Gets the value of the trueHeading property.
     * 
     */
    public double getTrueHeading() {
        return trueHeading;
    }

    /**
     * Sets the value of the trueHeading property.
     * 
     */
    public void setTrueHeading(double value) {
        this.trueHeading = value;
    }

    /**
     * Gets the value of the callSign property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCallSign() {
        return callSign;
    }

    /**
     * Sets the value of the callSign property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCallSign(String value) {
        this.callSign = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the dimensionLength property.
     * 
     */
    public int getDimensionLength() {
        return dimensionLength;
    }

    /**
     * Sets the value of the dimensionLength property.
     * 
     */
    public void setDimensionLength(int value) {
        this.dimensionLength = value;
    }

    /**
     * Gets the value of the dimensionWidth property.
     * 
     */
    public int getDimensionWidth() {
        return dimensionWidth;
    }

    /**
     * Sets the value of the dimensionWidth property.
     * 
     */
    public void setDimensionWidth(int value) {
        this.dimensionWidth = value;
    }

    /**
     * Gets the value of the etAmonth property.
     * 
     */
    public int getETAmonth() {
        return etAmonth;
    }

    /**
     * Sets the value of the etAmonth property.
     * 
     */
    public void setETAmonth(int value) {
        this.etAmonth = value;
    }

    /**
     * Gets the value of the etAday property.
     * 
     */
    public int getETAday() {
        return etAday;
    }

    /**
     * Sets the value of the etAday property.
     * 
     */
    public void setETAday(int value) {
        this.etAday = value;
    }

    /**
     * Gets the value of the etAhour property.
     * 
     */
    public int getETAhour() {
        return etAhour;
    }

    /**
     * Sets the value of the etAhour property.
     * 
     */
    public void setETAhour(int value) {
        this.etAhour = value;
    }

    /**
     * Gets the value of the etAminute property.
     * 
     */
    public int getETAminute() {
        return etAminute;
    }

    /**
     * Sets the value of the etAminute property.
     * 
     */
    public void setETAminute(int value) {
        this.etAminute = value;
    }

    /**
     * Gets the value of the maxDraught property.
     * 
     */
    public int getMaxDraught() {
        return maxDraught;
    }

    /**
     * Sets the value of the maxDraught property.
     * 
     */
    public void setMaxDraught(int value) {
        this.maxDraught = value;
    }

    /**
     * Gets the value of the destination property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDestination() {
        return destination;
    }

    /**
     * Sets the value of the destination property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDestination(String value) {
        this.destination = value;
    }

    /**
     * Gets the value of the altitudeGNSS property.
     * 
     */
    public int getAltitudeGNSS() {
        return altitudeGNSS;
    }

    /**
     * Sets the value of the altitudeGNSS property.
     * 
     */
    public void setAltitudeGNSS(int value) {
        this.altitudeGNSS = value;
    }

    /**
     * Gets the value of the bSurfaceTrack property.
     * 
     */
    public boolean isBSurfaceTrack() {
        return bSurfaceTrack;
    }

    /**
     * Sets the value of the bSurfaceTrack property.
     * 
     */
    public void setBSurfaceTrack(boolean value) {
        this.bSurfaceTrack = value;
    }

    /**
     * Gets the value of the bMobileTrack property.
     * 
     */
    public boolean isBMobileTrack() {
        return bMobileTrack;
    }

    /**
     * Sets the value of the bMobileTrack property.
     * 
     */
    public void setBMobileTrack(boolean value) {
        this.bMobileTrack = value;
    }

    /**
     * Gets the value of the bSensorSite property.
     * 
     */
    public boolean isBSensorSite() {
        return bSensorSite;
    }

    /**
     * Sets the value of the bSensorSite property.
     * 
     */
    public void setBSensorSite(boolean value) {
        this.bSensorSite = value;
    }

    /**
     * Gets the value of the bClassA property.
     * 
     */
    public boolean isBClassA() {
        return bClassA;
    }

    /**
     * Sets the value of the bClassA property.
     * 
     */
    public void setBClassA(boolean value) {
        this.bClassA = value;
    }

}
