//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.19 at 01:24:49 PM PDT 
//


package com.spawar.icode.radar;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for track_air_t complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="track_air_t">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="condition" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="md_3a_validity" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="md_c_validity" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="Mode3A" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="bMode2Valid" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="mode2" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="radar_num" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="callsign" type="{http://www.suretrak21.com/ST_Track}name33_t"/>
 *         &lt;element name="extAAHorzSep" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="extAAVertSep" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="extAALookAhead" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="extAAHorizBuf" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="extAAVertExten" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="extAADebugFlag" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="extAAVertVel" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="precisionAltDiff" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="bPrecisionAltDiffSet" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="bHDVertVel" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="bHDHorizVel" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="bHDDirChange" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="bHighDynamic" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="sensorMode3" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="bSensorMode3Valid" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="sensorMode2" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="bSensorMode2Valid" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="sensorCondition" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="aisSup" type="{http://www.suretrak21.com/ST_Track}sup_ais_data_t"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "track_air_t", propOrder = {
    "condition",
    "md3AValidity",
    "mdCValidity",
    "mode3A",
    "bMode2Valid",
    "mode2",
    "radarNum",
    "callsign",
    "extAAHorzSep",
    "extAAVertSep",
    "extAALookAhead",
    "extAAHorizBuf",
    "extAAVertExten",
    "extAADebugFlag",
    "extAAVertVel",
    "precisionAltDiff",
    "bPrecisionAltDiffSet",
    "bhdVertVel",
    "bhdHorizVel",
    "bhdDirChange",
    "bHighDynamic",
    "sensorMode3",
    "bSensorMode3Valid",
    "sensorMode2",
    "bSensorMode2Valid",
    "sensorCondition",
    "aisSup"
})
public class TrackAirT {

    protected long condition;
    @XmlElement(name = "md_3a_validity")
    protected boolean md3AValidity;
    @XmlElement(name = "md_c_validity")
    protected boolean mdCValidity;
    @XmlElement(name = "Mode3A")
    protected short mode3A;
    protected boolean bMode2Valid;
    protected short mode2;
    @XmlElement(name = "radar_num")
    protected short radarNum;
    @XmlElement(required = true)
    protected String callsign;
    protected double extAAHorzSep;
    protected int extAAVertSep;
    protected double extAALookAhead;
    protected double extAAHorizBuf;
    protected int extAAVertExten;
    protected int extAADebugFlag;
    protected int extAAVertVel;
    protected double precisionAltDiff;
    protected boolean bPrecisionAltDiffSet;
    @XmlElement(name = "bHDVertVel")
    protected boolean bhdVertVel;
    @XmlElement(name = "bHDHorizVel")
    protected boolean bhdHorizVel;
    @XmlElement(name = "bHDDirChange")
    protected boolean bhdDirChange;
    protected boolean bHighDynamic;
    protected short sensorMode3;
    protected boolean bSensorMode3Valid;
    protected short sensorMode2;
    protected boolean bSensorMode2Valid;
    protected long sensorCondition;
    @XmlElement(required = true)
    protected SupAisDataT aisSup;

    /**
     * Gets the value of the condition property.
     * 
     */
    public long getCondition() {
        return condition;
    }

    /**
     * Sets the value of the condition property.
     * 
     */
    public void setCondition(long value) {
        this.condition = value;
    }

    /**
     * Gets the value of the md3AValidity property.
     * 
     */
    public boolean isMd3AValidity() {
        return md3AValidity;
    }

    /**
     * Sets the value of the md3AValidity property.
     * 
     */
    public void setMd3AValidity(boolean value) {
        this.md3AValidity = value;
    }

    /**
     * Gets the value of the mdCValidity property.
     * 
     */
    public boolean isMdCValidity() {
        return mdCValidity;
    }

    /**
     * Sets the value of the mdCValidity property.
     * 
     */
    public void setMdCValidity(boolean value) {
        this.mdCValidity = value;
    }

    /**
     * Gets the value of the mode3A property.
     * 
     */
    public short getMode3A() {
        return mode3A;
    }

    /**
     * Sets the value of the mode3A property.
     * 
     */
    public void setMode3A(short value) {
        this.mode3A = value;
    }

    /**
     * Gets the value of the bMode2Valid property.
     * 
     */
    public boolean isBMode2Valid() {
        return bMode2Valid;
    }

    /**
     * Sets the value of the bMode2Valid property.
     * 
     */
    public void setBMode2Valid(boolean value) {
        this.bMode2Valid = value;
    }

    /**
     * Gets the value of the mode2 property.
     * 
     */
    public short getMode2() {
        return mode2;
    }

    /**
     * Sets the value of the mode2 property.
     * 
     */
    public void setMode2(short value) {
        this.mode2 = value;
    }

    /**
     * Gets the value of the radarNum property.
     * 
     */
    public short getRadarNum() {
        return radarNum;
    }

    /**
     * Sets the value of the radarNum property.
     * 
     */
    public void setRadarNum(short value) {
        this.radarNum = value;
    }

    /**
     * Gets the value of the callsign property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCallsign() {
        return callsign;
    }

    /**
     * Sets the value of the callsign property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCallsign(String value) {
        this.callsign = value;
    }

    /**
     * Gets the value of the extAAHorzSep property.
     * 
     */
    public double getExtAAHorzSep() {
        return extAAHorzSep;
    }

    /**
     * Sets the value of the extAAHorzSep property.
     * 
     */
    public void setExtAAHorzSep(double value) {
        this.extAAHorzSep = value;
    }

    /**
     * Gets the value of the extAAVertSep property.
     * 
     */
    public int getExtAAVertSep() {
        return extAAVertSep;
    }

    /**
     * Sets the value of the extAAVertSep property.
     * 
     */
    public void setExtAAVertSep(int value) {
        this.extAAVertSep = value;
    }

    /**
     * Gets the value of the extAALookAhead property.
     * 
     */
    public double getExtAALookAhead() {
        return extAALookAhead;
    }

    /**
     * Sets the value of the extAALookAhead property.
     * 
     */
    public void setExtAALookAhead(double value) {
        this.extAALookAhead = value;
    }

    /**
     * Gets the value of the extAAHorizBuf property.
     * 
     */
    public double getExtAAHorizBuf() {
        return extAAHorizBuf;
    }

    /**
     * Sets the value of the extAAHorizBuf property.
     * 
     */
    public void setExtAAHorizBuf(double value) {
        this.extAAHorizBuf = value;
    }

    /**
     * Gets the value of the extAAVertExten property.
     * 
     */
    public int getExtAAVertExten() {
        return extAAVertExten;
    }

    /**
     * Sets the value of the extAAVertExten property.
     * 
     */
    public void setExtAAVertExten(int value) {
        this.extAAVertExten = value;
    }

    /**
     * Gets the value of the extAADebugFlag property.
     * 
     */
    public int getExtAADebugFlag() {
        return extAADebugFlag;
    }

    /**
     * Sets the value of the extAADebugFlag property.
     * 
     */
    public void setExtAADebugFlag(int value) {
        this.extAADebugFlag = value;
    }

    /**
     * Gets the value of the extAAVertVel property.
     * 
     */
    public int getExtAAVertVel() {
        return extAAVertVel;
    }

    /**
     * Sets the value of the extAAVertVel property.
     * 
     */
    public void setExtAAVertVel(int value) {
        this.extAAVertVel = value;
    }

    /**
     * Gets the value of the precisionAltDiff property.
     * 
     */
    public double getPrecisionAltDiff() {
        return precisionAltDiff;
    }

    /**
     * Sets the value of the precisionAltDiff property.
     * 
     */
    public void setPrecisionAltDiff(double value) {
        this.precisionAltDiff = value;
    }

    /**
     * Gets the value of the bPrecisionAltDiffSet property.
     * 
     */
    public boolean isBPrecisionAltDiffSet() {
        return bPrecisionAltDiffSet;
    }

    /**
     * Sets the value of the bPrecisionAltDiffSet property.
     * 
     */
    public void setBPrecisionAltDiffSet(boolean value) {
        this.bPrecisionAltDiffSet = value;
    }

    /**
     * Gets the value of the bhdVertVel property.
     * 
     */
    public boolean isBHDVertVel() {
        return bhdVertVel;
    }

    /**
     * Sets the value of the bhdVertVel property.
     * 
     */
    public void setBHDVertVel(boolean value) {
        this.bhdVertVel = value;
    }

    /**
     * Gets the value of the bhdHorizVel property.
     * 
     */
    public boolean isBHDHorizVel() {
        return bhdHorizVel;
    }

    /**
     * Sets the value of the bhdHorizVel property.
     * 
     */
    public void setBHDHorizVel(boolean value) {
        this.bhdHorizVel = value;
    }

    /**
     * Gets the value of the bhdDirChange property.
     * 
     */
    public boolean isBHDDirChange() {
        return bhdDirChange;
    }

    /**
     * Sets the value of the bhdDirChange property.
     * 
     */
    public void setBHDDirChange(boolean value) {
        this.bhdDirChange = value;
    }

    /**
     * Gets the value of the bHighDynamic property.
     * 
     */
    public boolean isBHighDynamic() {
        return bHighDynamic;
    }

    /**
     * Sets the value of the bHighDynamic property.
     * 
     */
    public void setBHighDynamic(boolean value) {
        this.bHighDynamic = value;
    }

    /**
     * Gets the value of the sensorMode3 property.
     * 
     */
    public short getSensorMode3() {
        return sensorMode3;
    }

    /**
     * Sets the value of the sensorMode3 property.
     * 
     */
    public void setSensorMode3(short value) {
        this.sensorMode3 = value;
    }

    /**
     * Gets the value of the bSensorMode3Valid property.
     * 
     */
    public boolean isBSensorMode3Valid() {
        return bSensorMode3Valid;
    }

    /**
     * Sets the value of the bSensorMode3Valid property.
     * 
     */
    public void setBSensorMode3Valid(boolean value) {
        this.bSensorMode3Valid = value;
    }

    /**
     * Gets the value of the sensorMode2 property.
     * 
     */
    public short getSensorMode2() {
        return sensorMode2;
    }

    /**
     * Sets the value of the sensorMode2 property.
     * 
     */
    public void setSensorMode2(short value) {
        this.sensorMode2 = value;
    }

    /**
     * Gets the value of the bSensorMode2Valid property.
     * 
     */
    public boolean isBSensorMode2Valid() {
        return bSensorMode2Valid;
    }

    /**
     * Sets the value of the bSensorMode2Valid property.
     * 
     */
    public void setBSensorMode2Valid(boolean value) {
        this.bSensorMode2Valid = value;
    }

    /**
     * Gets the value of the sensorCondition property.
     * 
     */
    public long getSensorCondition() {
        return sensorCondition;
    }

    /**
     * Sets the value of the sensorCondition property.
     * 
     */
    public void setSensorCondition(long value) {
        this.sensorCondition = value;
    }

    /**
     * Gets the value of the aisSup property.
     * 
     * @return
     *     possible object is
     *     {@link SupAisDataT }
     *     
     */
    public SupAisDataT getAisSup() {
        return aisSup;
    }

    /**
     * Sets the value of the aisSup property.
     * 
     * @param value
     *     allowed object is
     *     {@link SupAisDataT }
     *     
     */
    public void setAisSup(SupAisDataT value) {
        this.aisSup = value;
    }

}
